name: Bug Report
description: Report a bug in Zeus

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which component of the code is the source of the bug?
      options:
        - core
        - models
        - Don't know / other
      multiple: true
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
    id: exception-or-error
    attributes:
      label: Please provide the exception or error you saw
      render: true

  - type: textarea
    id: environment
    attributes:
      label: Please provide the environment you discovered this bug in
      render: true
      placeholder: |
        Details about OS, environment, Python version, etc

  - type: textarea
    id: other
    attributes:
      label: Anything else?