name: 'Feature Request'
description: Suggest a feature for Zeus

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which of the following module(s) is/are relevant/releated to the feature request?
      options:
        - core
        - models
        - other
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true